spring:
  application.name: Chat Service
  profiles.active: ${SPRING_PROFILE:local}
  data.mongodb.uri: ${CHAT_DB_URI:mongodb://root:password@localhost:27017/chat_db?authSource=admin}
  ai:
    anthropic:
      api-key: ${ANTHROPIC_API_KEY}
      model: claude-3.5-haiku
    mcp.client:
      sse.connections.weather-server:
        url: http://localhost:8090/
        enabled: true
      toolcallback.enabled: true
logging.level.org.springframework.web: DEBUG
